spring:
  config:
    import: optional:file:.env
  datasourse:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secrets.DB_URL}
    username: ${secrets.DB_USER}
    password: ${secrets.DB_PW}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: travel_korea
server:
  port: 8080
